# Parse Keys
APP_ID       = 'QN2IxFFiHCTm0oKSgI6KafqJJQ3nAxwQD8QiqrYZ'
JS_KEY       = 'R80kznvL5F5VEzAHQ0lRwsh9iEJ3EIDdZqv1AYmJ'
REST_API_KEY = 'JGo5nsMzMHzODoKX70rpKh1SLQuFcTBVGnxcQp3v'

# Google Maps JS API Key
GOOGLE_MAPS_API_KEY = 'AIzaSyDRmTMkNWPB6dEq-xIlhr02W_QfO-9O1xI'